symphonet/symphonet/urls.py
from django.contrib import admin
from django.urls import path
from symphonet1 import views
from django.contrib import admin
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('symphonet/', include('symphonet1.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

symphonet/symphonet1/urls.py
from django.urls import path
from django.conf.urls import url
from symphonet1 import views

app_name = 'symphonet'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name='about_us'),
    path('account/', views.account, name='account'),
    path('songs/', views.SongListView.as_view(), name="songs"),
    path('songs/<int:page>',views.songs, name="songs_by_page"),
    path('songs/<int:songid>/reviews/', views.song_review, name='song_review'),
    path('songs/<int:songid>/make_review/', views.make_review, name='make_review'),
    path('account/myreviews', views.user_reviews, name='user_reviews'),
    path('account/myplaylists', views.playlists, name='playlists'),
    path('add_playlist/', views.add_playlist, name='add_playlist'),
    path('profile/<int:user_id>/', views.user_profile, name='user_profile'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.user_login, name='user_login'),
    path('logout/',views.user_logout, name="logout"),
    path('add_friends/', views.add_friends, name='add_friends'), 
    path('add_friends_submit/', views.add_friends_submit, name='add_friends_submit'),
    path('remove_friends/', views.remove_friends, name='remove_friends'), 
    path('remove_friends_submit/', views.remove_friends_submit, name='remove_friends_submit'),
    
]

symphonet/templates/symphonet/about_us.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Symphonet
{% endblock %}
<link rel="stylesheet" type="text/css" href="{% static 'style/about.css' %}">

{% block body_block %}
    <div class="about-section">
        <p>Welcome to symphonet!</p>
        <p>Symphonet is a music platform dedicated to letting music lovers a place to share and enjoy music with their friends!</p>
        <p>Users can rate songs and create playlists and artists can add new songs and albums to the site!</p>
    </div>



{% endblock %}

symphonet/templates/symphonet/account.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}

<!-- Should eventually be username -->
{% block title_block %}
    Profile
{% endblock %}

{% block body_block %}
<div class="container">
    <h2>Your Playlists</h2>
        <div class="container-fluid bg-light">
        <a href="{% url 'symphonet:add_playlist' %}">new playlist</a>
        {% if playlists %}
            {% for playlist in playlists %}
                <p>{{ playlist.name }}</p>
            {% endfor %}
        {% else %}
            <p>No playlists currently.</p>
        {% endif %}
        </div>

    <h2>Your Top Ratings</h2>
        <div class="container-fluid bg-light">
        <a href="{% url 'symphonet:user_reviews' %}">My Reviews</a>
        {% if ratings %}
            {% for rating in ratings %}
                {{ rating.song.name }}
                {{ rating.score }}
            {% endfor %}
        {% else %}
            <p>No reviews currently.</p>
        {% endif %}
        </div>

    <div>
        <h2>Your Friends</h2>
        {% if friends %}
            <ul>
                {% for friend_profile in friends %}
                    <li><a href="{% url 'symphonet:user_profile' friend_profile.user.id %}">{{ friend_profile.user.username }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>You don't have any friends yet.</p>
        {% endif %}
    </div>

    <div>
        <a href="{% url 'symphonet:add_friends' %}">Add Friends</a>
    </div>

    <div>
        <a href="{% url 'symphonet:remove_friends' %}">Remove Friends</a>
    </div>
</div>
{% endblock %}

symphonet/templates/symphonet/add_friends.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}

{% block body_block %}
  <h2>Add Friends</h2>
  {% if users %}
    <form action="{% url 'symphonet:add_friends_submit' %}" method="post">
      {% csrf_token %}
      <ul>
        {% for user in users %}
          <li>
            <input type="checkbox" name="friends" value="{{ user.pk }}"> {{ user.username }}
          </li>
        {% endfor %}
      </ul>
      <button type="submit">Add Selected Friends</button>
    </form>
  {% else %}
    <p>No other users to add as friends.</p>
    <a href="{% url 'symphonet:account' %}">Return to Account</a>
  {% endif %}
{% endblock %}

symphonet/templates/symphonet/add_playlist.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}

{% block title_block %}
    User's Playlists
{% endblock %}

{% block body_block %}
    <div>
        <h2>Add Playlist</h2>
    </div>
    <form id="playlist_form" method="post" action="{% url 'symphonet:add_playlist' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type ="submit" name="submit" value="Create Playlist" />
    </form>
{% endblock %}

symphonet/templates/symphonet/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Symphonet -
        {% block title_block %}
        Symphonet
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style/base.css' %}">

    {% block style_block %}
        <!-- Page specific stylesheets enter here -->
    {% endblock %}
</head>

<body>
    <div class="container-fluid">
        <div class="p-5 row">
            <div class="col-sm-4"><h1>SymphoNet</h1></div>
            {% if user.is_authenticated %}
                <div class="col-sm-8">
                    <div class="float-end">
                    <h2>Welcome {{ user.username }}</h2>
                    <a href="{% url 'symphonet:logout' %}" class="btn btn-dark pull-right" role="button">Logout</a>
                    </div>
                </div>
            {% else %}
                <div class="col-sm-8">
                    <div class="btn-group float-end">
                    <a href="{% url 'symphonet:sign_up' %}" class="btn btn-dark" role="button">Sign Up</a>
                    <a href="{% url 'symphonet:user_login' %}" class="btn btn-dark" role="button">Login</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

    <nav class="navbar navbar-expand-sm navbar-expand-md navbar-expand-lg bg-dark">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="navbar-brand" href="{% url 'symphonet:index' %}"><img src="{% static 'images/home-icon.png' %}" alt="home icon" /></a>
            </li>
            <li class="nav-item">
                <a class="navbar-brand" href="{% url 'symphonet:about_us' %}"><img src="{% static 'images/about-icon.png' %}" alt="about icon" /></a>
            </li>
            <li class="nav-item">
                <a class="navbar-brand" href="{% url 'symphonet:songs' %}"><img src="{% static 'images/music-icon.png' %}" alt="song icon" /></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="navbar-brand" href="{% url 'symphonet:account' %}"><img src="{% static 'images/profile-icon.png' %}" alt="account icon" /></a>
            </li>
            {% endif %}
          </ul>
        </div>
    </nav>

    {% block body_block %}
    {% endblock %}
</body>

</html>

symphonet/templates/symphonet/index.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Index
{% endblock %}

{% block body_block %}
<body>
    <h1> Trending</h1> 
    <h3>Top Five Rated Artists</h3>
    {% if artists %}
    <ul>
        {% for artist in artists %}
            <li>{{ artist.name }}</li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>There are no artists present.</strong>
    {% endif %}

    <h3>Top Five Rated Albums</h3>
    {% if albums %}
    <ul>
        {% for album in albums %}
            <li>{{ album.name }}</li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>There are no albums present.</strong>
    {% endif %}

    <h3>Top Five Rated Songs</h3>
    {% if songs %}
    <ul>
        {% for song in songs %}
            <li>{{ song.name }}</li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>There are no songs present.</strong>
    {% endif %}
</body>
{% endblock %}

symphonet/templates/symphonet/login.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}

<html lang="en">

{% block title_block %}
Login
{% endblock %}

{% block style_block %}

{% endblock %}

{% block body_block %}
<div class="login-container">
    <div class="login-form">
        <!--
        <div class="mb-3">
            <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="addon-wrapping">
        </div>
        <div class="mb-3">
            <input type="password" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="addon-wrapping">
        </div>
    -->
        {% if user.is_authenticated %}
        welcome to symphonet {{ user.username }}
        <a href="{% url 'symphonet:index' %}">Main Page</a>
        {% else %}
        <form id="login_form" method="post" action="{% url 'symphonet:user_login' %}">

            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="30" /> <br />
            Password: <input type="password" name="password" value="" size="30" /> <br />

            <div class="btn-container">
                <input type="submit" class="btn" value="login" />
            </div>
            <div class="btn-container">
                <button type="button" class="btn" onclick="window.location.href='{% url 'symphonet:sign_up' %}'"><!--There is no error here even tho it has a red marker,it works fine-->
                    Sign up
                </button>                
            </div>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

</html>

symphonet/templates/symphonet/make_review.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}

{% block body_block %}
    
    <!-- Display any form errors -->
    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            Please correct the following errors.
        </div>
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ field.label }}:</strong> {{ error }}
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}
    
    <!-- The form itself -->
    <form method="post" action="{% url 'symphonet:make_review' song.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="song" value="{{ song.id }}" />
        <button type="submit" class="btn btn-primary">Submit Review</button>
    </form>
    
    <!-- Back to song reviews page, adjust URL as necessary -->
    <a href="{% url 'symphonet:song_review' song.id %}" class="btn btn-secondary">Back to Reviews</a>
{% endblock %}

symphonet/templates/symphonet/my_reviews.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}
<!-- Should eventually be username -->
{% block title_block %}
    Profile's Reviews
{% endblock %}

{% block body_block %}
    <div>
        <h2>Your Reviews</h2>
    </div>

    <div>
        {% if reviews %}
        <ul>
            {% for review in reviews %}
                <li> {{ review.song }} - Rating of {{ review.score }} /5 </li>
            {% endfor %}
        </ul>
        {% else %}
            <strong> You have not rated any songs yet</strong>
        {% endif %}
    </div>
{% endblock %}

symphonet/templates/symphonet/playlists.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}

{% block title_block %}
    User's Playlists
{% endblock %}

{% block body_block %}
    <div>
        <h2>Your Playlists</h2>
    </div>
    {% if playlists %}
        {% for playlist in playlists %}
            <p> {{playlist.name}} </p>
        {% endfor %}
    {% else %}
        <p>No Playlists currently</p>
    {% endif %}
{% endblock %}

symphonet/templates/symphonet/remove_friends.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}

{% block body_block %}
  <h2>Remove Friends</h2>
  {% if friends %}
    <form action="{% url 'symphonet:remove_friends_submit' %}" method="post">
      {% csrf_token %}
      <ul>
        {% for friend in friends %}
          <li>
            <input type="checkbox" name="friends" value="{{ friend.pk }}"> {{ friend.user.username }}
          </li>
        {% endfor %}
      </ul>
      <button type="submit">Remove Selected Friends</button>
    </form>
  {% else %}
    <p>No friends to remove.</p>
    <a href="{% url 'symphonet:account' %}">Return to Account</a>
  {% endif %}
{% endblock %}

symphonet/templates/symphonet/sign_up.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}
<html lang="en">

{% block title_block %}
Sign Up
{% endblock %}

{% block style_block %}

{% endblock %}

{% block body_block %}
<div class="login-form"> 

    
   
    {% if registered %}
        <p> thank you for signing up</p>
        <a href = "{% url 'symphonet:index' %}">Main Page</a>
    {% else %}
    <form id="user_form" method = "post" action="{% url 'symphonet:sign_up' %}" enctype = "multipart/form-data">

        {% csrf_token %}

        {{ user_form.as_p }}
        {{ profile_form.as_p }}
       
        <div class="btn-container">
            <input type="submit" class="btn" name = "submit" value="Sign up">
        </div>
        <div class="btn-container">
            <button type="button" class="btn" onclick="window.location.href='{% url 'symphonet:user_login' %}'"><!--There is no error here even tho it has a red marker,it works fine-->
                Login
            </button>  
        </div>
       
    </form>
    {% endif %}
    
</div>
{% endblock %}

</html>

symphonet/templates/symphonet/songs.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Songs
{% endblock %}

{% block body_block %}
    <h2>All Songs</h2>
    {% block content %}
        {% for song in page_obj %}
            <a href="{% url 'symphonet:song_review' song.id %}">
            {{song.name}} - {{song.artist}}
            </a>
            </br>
        {% endfor %}
    {% endblock %}

    {% block pagination %}
        {% for page_number in page_obj.paginator.page_range %}
            <a href="{% url 'symphonet:songs_by_page' page_number %}"
            class="{% if page_number == page_obj.number %}current{% endif %}">{{page_number}}</a>    
        {% endfor %}
    {% endblock %}
{% endblock %}

symphonet/templates/symphonet/user_profile.html
{% extends 'symphonet/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Profile
{% endblock %}

{% block body_block %}
<div class="container">
    <h2>{{ user_profile }}'s Playlists </h2>
        <div class="container-fluid bg-light">
        {% if playlists %}
            {% for playlist in playlists %}
                <p>{{ playlist.name }}</p>
            {% endfor %}
        {% else %}
            <p>No playlists currently.</p>
        {% endif %}
        </div>

    <h2>{{ user_profile }}'s Top Ratings</h2>
        <div class="container-fluid bg-light">
        {% if ratings %}
            <ul>
            {% for rating in ratings %}
                <li>{{ rating.song.name }} - {{ rating.score }}</li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No reviews currently.</p>
        {% endif %}
        </div>

</div>
{% endblock %}